# Theme: Ayu Light
# Source: https://github.com/dempfi/ayu

background              #FAFAFA
foreground              #575F66
cursor                  #FF6A00
selection_background    #D3D3D3
selection_foreground    #575F66

# Normal colors (0-7)
color0  #0A0E14
color1  #FF3333
color2  #86B300
color3  #F29718
color4  #41A6D9
color5  #A37ACC
color6  #4DBF99
color7  #BFBDB6

# Bright colors (8-15)
color8  #5C6773
color9  #FF6565
color10 #B8CC52
color11 #FFB454
color12 #73D8FF
color13 #D4BFFF
color14 #95E6CB
color15 #FFFFFF
