# Theme: Material Dark
# Source: https://material-theme.com

background              #212121
foreground              #EEFFFF
cursor                  #FFCC00
selection_background    #546E7A
selection_foreground    #EEFFFF

# Normal colors (0-7)
color0  #546E7A
color1  #FF5370
color2  #C3E88D
color3  #FFCB6B
color4  #82AAFF
color5  #C792EA
color6  #89DDFF
color7  #EEFFFF

# Bright colors (8-15)
color8  #B0BEC5
color9  #FF5370
color10 #C3E88D
color11 #FFCB6B
color12 #82AAFF
color13 #C792EA
color14 #89DDFF
color15 #FFFFFF
