# Theme: Nightfox
# Source: https://github.com/EdenEast/nightfox.nvim

background              #192330
foreground              #CDCECF
cursor                  #CDCECF
selection_background    #2B3B51
selection_foreground    #CDCECF

# Normal colors (0-7)
color0  #393B44
color1  #C94F6D
color2  #81B29A
color3  #DBC074
color4  #719CD6
color5  #9D79D6
color6  #63CDCF
color7  #DFDFE0

# Bright colors (8-15)
color8  #575860
color9  #D16983
color10 #8EBD9B
color11 #E0C989
color12 #86ABDC
color13 #B48EAD
color14 #7AD5D6
color15 #E4E4E5
