# Theme: One Dark
# Source: https://github.com/atom/atom

background              #282C34
foreground              #ABB2BF
cursor                  #528BFF
selection_background    #3E4451
selection_foreground    #ABB2BF

# Normal colors (0-7)
color0  #282C34
color1  #E06C75
color2  #98C379
color3  #E5C07B
color4  #61AFEF
color5  #C678DD
color6  #56B6C2
color7  #ABB2BF

# Bright colors (8-15)
color8  #5C6370
color9  #E06C75
color10 #98C379
color11 #E5C07B
color12 #61AFEF
color13 #C678DD
color14 #56B6C2
color15 #FFFFFF
