# Theme: Ayu Light
# Source: https://github.com/dempfi/ayu
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(FAFAFA)
$color_foreground = rgb(575F66)
$color_cursor     = rgb(FF6A00)
$color_selection  = rgb(D3D3D3)

$color_black      = rgb(0A0E14)
$color_red        = rgb(FF3333)
$color_green      = rgb(86B300)
$color_yellow     = rgb(F29718)
$color_blue       = rgb(41A6D9)
$color_magenta    = rgb(A37ACC)
$color_cyan       = rgb(4DBF99)
$color_white      = rgb(BFBDB6)

$color_bright_black   = rgb(5C6773)
$color_bright_red     = rgb(FF6565)
$color_bright_green   = rgb(B8CC52)
$color_bright_yellow  = rgb(FFB454)
$color_bright_blue    = rgb(73D8FF)
$color_bright_magenta = rgb(D4BFFF)
$color_bright_cyan    = rgb(95E6CB)
$color_bright_white   = rgb(FFFFFF)
