# Theme: Modus Vivendi
# Source: https://protesilaos.com/emacs/modus-themes
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(000000)
$color_foreground = rgb(FFFFFF)
$color_cursor     = rgb(FFFFFF)
$color_selection  = rgb(2C2C2C)

$color_black      = rgb(1E1E1E)
$color_red        = rgb(FF5F5F)
$color_green      = rgb(44BC44)
$color_yellow     = rgb(D0BC00)
$color_blue       = rgb(2FAFFF)
$color_magenta    = rgb(FEACD0)
$color_cyan       = rgb(00D3D0)
$color_white      = rgb(D0D0D0)

$color_bright_black   = rgb(595959)
$color_bright_red     = rgb(FF7F9F)
$color_bright_green   = rgb(70C900)
$color_bright_yellow  = rgb(EFEF00)
$color_bright_blue    = rgb(79A8FF)
$color_bright_magenta = rgb(F78FE7)
$color_bright_cyan    = rgb(4AE2F0)
$color_bright_white   = rgb(FFFFFF)
