# Theme: Monokai
# Source: https://monokai.pro
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(272822)
$color_foreground = rgb(F8F8F2)
$color_cursor     = rgb(F8F8F2)
$color_selection  = rgb(75715E)

$color_black      = rgb(272822)
$color_red        = rgb(F92672)
$color_green      = rgb(A6E22E)
$color_yellow     = rgb(F4BF75)
$color_blue       = rgb(66D9E8)
$color_magenta    = rgb(AE81FF)
$color_cyan       = rgb(A1EFE4)
$color_white      = rgb(F8F8F2)

$color_bright_black   = rgb(75715E)
$color_bright_red     = rgb(F92672)
$color_bright_green   = rgb(A6E22E)
$color_bright_yellow  = rgb(F4BF75)
$color_bright_blue    = rgb(66D9E8)
$color_bright_magenta = rgb(AE81FF)
$color_bright_cyan    = rgb(A1EFE4)
$color_bright_white   = rgb(F9F8F5)
