# Theme: Nightfox
# Source: https://github.com/EdenEast/nightfox.nvim
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(192330)
$color_foreground = rgb(CDCECF)
$color_cursor     = rgb(CDCECF)
$color_selection  = rgb(2B3B51)

$color_black      = rgb(393B44)
$color_red        = rgb(C94F6D)
$color_green      = rgb(81B29A)
$color_yellow     = rgb(DBC074)
$color_blue       = rgb(719CD6)
$color_magenta    = rgb(9D79D6)
$color_cyan       = rgb(63CDCF)
$color_white      = rgb(DFDFE0)

$color_bright_black   = rgb(575860)
$color_bright_red     = rgb(D16983)
$color_bright_green   = rgb(8EBD9B)
$color_bright_yellow  = rgb(E0C989)
$color_bright_blue    = rgb(86ABDC)
$color_bright_magenta = rgb(B48EAD)
$color_bright_cyan    = rgb(7AD5D6)
$color_bright_white   = rgb(E4E4E5)
