# Theme: Palenight
# Source: https://github.com/whizkydee/vscode-palenight-theme
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(292d3e)
$color_foreground = rgb(a6accd)
$color_cursor     = rgb(a6accd)
$color_selection  = rgb(32374d)

$color_black      = rgb(292d3e)
$color_red        = rgb(f07178)
$color_green      = rgb(c3e88d)
$color_yellow     = rgb(ffcb6b)
$color_blue       = rgb(82aaff)
$color_magenta    = rgb(c792ea)
$color_cyan       = rgb(89ddff)
$color_white      = rgb(d0d0d0)

$color_bright_black   = rgb(434758)
$color_bright_red     = rgb(ff8b92)
$color_bright_green   = rgb(ddffa7)
$color_bright_yellow  = rgb(ffe585)
$color_bright_blue    = rgb(9cc4ff)
$color_bright_magenta = rgb(e1acff)
$color_bright_cyan    = rgb(a3f7ff)
$color_bright_white   = rgb(ffffff)
