# Theme: Rose Piné
# Source: https://rosepinetheme.com
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(191724)
$color_foreground = rgb(e0def4)
$color_cursor     = rgb(e0def4)
$color_selection  = rgb(403d52)

$color_black      = rgb(26233a)
$color_red        = rgb(eb6f92)
$color_green      = rgb(31748f)
$color_yellow     = rgb(f6c177)
$color_blue       = rgb(9ccfd8)
$color_magenta    = rgb(c4a7e7)
$color_cyan       = rgb(ebbcba)
$color_white      = rgb(e0def4)

$color_bright_black   = rgb(6e6a86)
$color_bright_red     = rgb(eb6f92)
$color_bright_green   = rgb(31748f)
$color_bright_yellow  = rgb(f6c177)
$color_bright_blue    = rgb(9ccfd8)
$color_bright_magenta = rgb(c4a7e7)
$color_bright_cyan    = rgb(ebbcba)
$color_bright_white   = rgb(e0def4)
