# Theme: Tokyo Night
# Source: https://github.com/enkia/tokyo-night-vscode-theme
# Include in hyprland.conf: source = ~/.config/hypr/colors.conf

$color_background = rgb(1A1B26)
$color_foreground = rgb(C0CAF5)
$color_cursor     = rgb(C0CAF5)
$color_selection  = rgb(283457)

$color_black      = rgb(15161E)
$color_red        = rgb(F7768E)
$color_green      = rgb(9ECE6A)
$color_yellow     = rgb(E0AF68)
$color_blue       = rgb(7AA2F7)
$color_magenta    = rgb(BB9AF7)
$color_cyan       = rgb(7DCFFF)
$color_white      = rgb(A9B1D6)

$color_bright_black   = rgb(414868)
$color_bright_red     = rgb(F7768E)
$color_bright_green   = rgb(9ECE6A)
$color_bright_yellow  = rgb(E0AF68)
$color_bright_blue    = rgb(7AA2F7)
$color_bright_magenta = rgb(BB9AF7)
$color_bright_cyan    = rgb(7DCFFF)
$color_bright_white   = rgb(C0CAF5)
