# Theme: Ayu Light
# Source: https://github.com/dempfi/ayu
# Usage: include in ~/.config/foot/foot.ini:
#   include=~/.config/foot/themes/ayu-light.ini

[colors]
background=FAFAFA
foreground=575F66

selection-background=D3D3D3
selection-foreground=575F66

regular0=0A0E14
regular1=FF3333
regular2=86B300
regular3=F29718
regular4=41A6D9
regular5=A37ACC
regular6=4DBF99
regular7=BFBDB6

bright0=5C6773
bright1=FF6565
bright2=B8CC52
bright3=FFB454
bright4=73D8FF
bright5=D4BFFF
bright6=95E6CB
bright7=FFFFFF
