version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      majors:
        update-types: ["major"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:40"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      majors:
        update-types: ["major"]
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:50"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      majors:
        update-types: ["major"]
