# Theme: Gruvbox Dark
# Source: https://github.com/morhetz/gruvbox

[colors.primary]
background = "#282828"
foreground = "#EBDBB2"

[colors.cursor]
cursor = "#EBDBB2"
text   = "#282828"

[colors.selection]
background = "#3C3836"
text       = "#EBDBB2"

[colors.normal]
black   = "#282828"
red     = "#CC241D"
green   = "#98971A"
yellow  = "#D79921"
blue    = "#458588"
magenta = "#B16286"
cyan    = "#689D6A"
white   = "#A89984"

[colors.bright]
black   = "#928374"
red     = "#FB4934"
green   = "#B8BB26"
yellow  = "#FABD2F"
blue    = "#83A598"
magenta = "#D3869B"
cyan    = "#8EC07C"
white   = "#EBDBB2"
