# Theme: Monokai
# Source: https://monokai.pro

[colors.primary]
background = "#272822"
foreground = "#F8F8F2"

[colors.cursor]
cursor = "#F8F8F2"
text   = "#272822"

[colors.selection]
background = "#75715E"
text       = "#F8F8F2"

[colors.normal]
black   = "#272822"
red     = "#F92672"
green   = "#A6E22E"
yellow  = "#F4BF75"
blue    = "#66D9E8"
magenta = "#AE81FF"
cyan    = "#A1EFE4"
white   = "#F8F8F2"

[colors.bright]
black   = "#75715E"
red     = "#F92672"
green   = "#A6E22E"
yellow  = "#F4BF75"
blue    = "#66D9E8"
magenta = "#AE81FF"
cyan    = "#A1EFE4"
white   = "#F9F8F5"
