# Theme: Rosé Pine Moon
# Source: https://rosepinetheme.com

[colors.primary]
background = "#232136"
foreground = "#E0DEF4"

[colors.cursor]
cursor = "#E0DEF4"
text   = "#232136"

[colors.selection]
background = "#44415A"
text       = "#E0DEF4"

[colors.normal]
black   = "#393552"
red     = "#EB6F92"
green   = "#3E8FB0"
yellow  = "#F6C177"
blue    = "#9CCFD8"
magenta = "#C4A7E7"
cyan    = "#EA9A97"
white   = "#E0DEF4"

[colors.bright]
black   = "#6E6A86"
red     = "#EB6F92"
green   = "#3E8FB0"
yellow  = "#F6C177"
blue    = "#9CCFD8"
magenta = "#C4A7E7"
cyan    = "#EA9A97"
white   = "#E0DEF4"
