# Theme: Solarized Dark
# Source: https://ethanschoonover.com/solarized/

[colors.primary]
background = "#002B36"
foreground = "#839496"

[colors.cursor]
cursor = "#839496"
text   = "#002B36"

[colors.selection]
background = "#073642"
text       = "#839496"

[colors.normal]
black   = "#073642"
red     = "#DC322F"
green   = "#859900"
yellow  = "#B58900"
blue    = "#268BD2"
magenta = "#D33682"
cyan    = "#2AA198"
white   = "#EEE8D5"

[colors.bright]
black   = "#002B36"
red     = "#CB4B16"
green   = "#586E75"
yellow  = "#657B83"
blue    = "#839496"
magenta = "#6C71C4"
cyan    = "#93A1A1"
white   = "#FDF6E3"
