# Theme: Ayu Light
# Source: https://github.com/dempfi/ayu
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#FAFAFA"
    foreground = "#575F66"
    frame_color = "#41A6D9"

[urgency_normal]
    background = "#FAFAFA"
    foreground = "#575F66"
    frame_color = "#41A6D9"

[urgency_critical]
    background = "#FF3333"
    foreground = "#FAFAFA"
    frame_color = "#FF6565"
