# Theme: Dracula
# Source: https://draculatheme.com
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#282A36"
    foreground = "#F8F8F2"
    frame_color = "#BD93F9"

[urgency_normal]
    background = "#282A36"
    foreground = "#F8F8F2"
    frame_color = "#BD93F9"

[urgency_critical]
    background = "#FF5555"
    foreground = "#282A36"
    frame_color = "#FF6E6E"
