# Theme: Material Dark
# Source: https://material-theme.com
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#212121"
    foreground = "#EEFFFF"
    frame_color = "#82AAFF"

[urgency_normal]
    background = "#212121"
    foreground = "#EEFFFF"
    frame_color = "#82AAFF"

[urgency_critical]
    background = "#FF5370"
    foreground = "#212121"
    frame_color = "#FF5370"
