# Theme: Modus Vivendi
# Source: https://protesilaos.com/emacs/modus-themes
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#000000"
    foreground = "#FFFFFF"
    frame_color = "#2FAFFF"

[urgency_normal]
    background = "#000000"
    foreground = "#FFFFFF"
    frame_color = "#2FAFFF"

[urgency_critical]
    background = "#FF5F5F"
    foreground = "#000000"
    frame_color = "#FF7F9F"
