# Theme: Nightfox
# Source: https://github.com/EdenEast/nightfox.nvim
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#192330"
    foreground = "#CDCECF"
    frame_color = "#719CD6"

[urgency_normal]
    background = "#192330"
    foreground = "#CDCECF"
    frame_color = "#719CD6"

[urgency_critical]
    background = "#C94F6D"
    foreground = "#192330"
    frame_color = "#D16983"
