# Theme: One Dark
# Source: https://github.com/atom/atom
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#282C34"
    foreground = "#ABB2BF"
    frame_color = "#61AFEF"

[urgency_normal]
    background = "#282C34"
    foreground = "#ABB2BF"
    frame_color = "#61AFEF"

[urgency_critical]
    background = "#E06C75"
    foreground = "#282C34"
    frame_color = "#E06C75"
