# Theme: Palenight
# Source: https://github.com/whizkydee/vscode-palenight-theme
# Include in dunstrc: [global] section, or source this file

[urgency_low]
    background = "#292d3e"
    foreground = "#a6accd"
    frame_color = "#82aaff"

[urgency_normal]
    background = "#292d3e"
    foreground = "#a6accd"
    frame_color = "#82aaff"

[urgency_critical]
    background = "#f07178"
    foreground = "#292d3e"
    frame_color = "#ff8b92"
