#!/usr/bin/env python3
"""
build_readme_stats.py — regenerate the auto-stats block in README.md from
meta/catalog.json, keeping the headline counts honest without hand-editing.

Replaces everything between the STATS:START / STATS:END markers with a summary
line and a per-category dataset/entry table. Run after build_catalog.py.

Run:  python3 tools/build_readme_stats.py            # rewrite the block
      python3 tools/build_readme_stats.py --check    # exit 1 if stale (CI)
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "<!-- STATS:START (auto-generated by tools/build_readme_stats.py — do not edit by hand) -->"
END = "<!-- STATS:END -->"


def render():
    cat = json.load(open(os.path.join(ROOT, "meta", "catalog.json"), encoding="utf-8"))
    per = {}
    for ds in cat["datasets"]:
        c = ds["category"]
        per.setdefault(c, [0, 0])
        per[c][0] += 1
        per[c][1] += ds["count"]

    lines = [START, ""]
    lines.append(f"**{cat['dataset_count']} datasets · {cat['entry_total']:,} entries · "
                 f"{cat['category_count']} categories** — "
                 f"authoritative sources mapped in [`meta/sources.json`](/meta/sources.json)")
    lines.append("")
    lines.append("<details><summary>Per-category breakdown</summary>")
    lines.append("")
    lines.append("| Category | Datasets | Entries |")
    lines.append("|---|--:|--:|")
    for c in sorted(per):
        d, e = per[c]
        lines.append(f"| {c} | {d} | {e:,} |")
    lines.append("")
    lines.append("</details>")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main():
    path = os.path.join(ROOT, "README.md")
    text = open(path, encoding="utf-8").read()
    if START not in text or END not in text:
        print("README.md is missing the STATS markers")
        sys.exit(1)
    pre = text.split(START)[0]
    post = text.split(END, 1)[1]
    new = pre + render() + post
    if "--check" in sys.argv[1:]:
        if new != text:
            print("README stats block is stale — run tools/build_readme_stats.py")
            sys.exit(1)
        print("README stats block up to date")
        return
    open(path, "w", encoding="utf-8").write(new)
    print("updated README.md stats block")


if __name__ == "__main__":
    main()
