-- Theme: Ayu Light
-- Source: https://github.com/dempfi/ayu
-- Usage: dofile(vim.fn.stdpath("config") .. "/lua/rice/ayu-light.lua")
--   or copy to ~/.config/nvim/colors/ayu-light.lua

local hi = vim.api.nvim_set_hl

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "ayu-light"

local is_light = true
vim.o.background = is_light and "light" or "dark"

-- Editor chrome
hi(0, "Normal",       { bg = "#FAFAFA", fg = "#575F66" })
hi(0, "NormalFloat",  { bg = "#0A0E14", fg = "#575F66" })
hi(0, "NormalNC",     { bg = "#FAFAFA", fg = "#5C6773" })
hi(0, "SignColumn",   { bg = "#FAFAFA" })
hi(0, "LineNr",       { fg = "#5C6773" })
hi(0, "CursorLine",   { bg = "#D3D3D3" })
hi(0, "CursorLineNr", { fg = "#575F66", bold = true })
hi(0, "CursorColumn", { bg = "#D3D3D3" })
hi(0, "Visual",       { bg = "#D3D3D3" })
hi(0, "VisualNOS",    { bg = "#D3D3D3" })
hi(0, "Search",       { bg = "#F29718", fg = "#FAFAFA" })
hi(0, "IncSearch",    { bg = "#FFB454", fg = "#FAFAFA" })
hi(0, "CurSearch",    { bg = "#FFB454", fg = "#FAFAFA" })
hi(0, "StatusLine",   { bg = "#0A0E14", fg = "#575F66" })
hi(0, "StatusLineNC", { bg = "#0A0E14", fg = "#5C6773" })
hi(0, "VertSplit",    { fg = "#5C6773" })
hi(0, "WinSeparator", { fg = "#5C6773" })
hi(0, "Folded",       { bg = "#0A0E14", fg = "#5C6773" })
hi(0, "FoldColumn",   { fg = "#5C6773" })
hi(0, "Conceal",      { fg = "#5C6773" })
hi(0, "ColorColumn",  { bg = "#0A0E14" })
hi(0, "Pmenu",        { bg = "#0A0E14", fg = "#575F66" })
hi(0, "PmenuSel",     { bg = "#41A6D9", fg = "#FAFAFA" })
hi(0, "PmenuSbar",    { bg = "#0A0E14" })
hi(0, "PmenuThumb",   { bg = "#5C6773" })
hi(0, "TabLine",      { bg = "#0A0E14", fg = "#5C6773" })
hi(0, "TabLineSel",   { bg = "#FAFAFA", fg = "#575F66", bold = true })
hi(0, "TabLineFill",  { bg = "#0A0E14" })
hi(0, "Title",        { fg = "#41A6D9", bold = true })
hi(0, "MatchParen",   { fg = "#4DBF99", bold = true })
hi(0, "Question",     { fg = "#86B300" })
hi(0, "Directory",    { fg = "#41A6D9" })
hi(0, "SpecialKey",   { fg = "#5C6773" })
hi(0, "NonText",      { fg = "#5C6773" })
hi(0, "Whitespace",   { fg = "#5C6773" })
hi(0, "EndOfBuffer",  { fg = "#5C6773" })
hi(0, "WildMenu",     { bg = "#41A6D9", fg = "#FAFAFA" })
hi(0, "DiffAdd",      { bg = "#FAFAFA", fg = "#86B300" })
hi(0, "DiffChange",   { bg = "#FAFAFA", fg = "#F29718" })
hi(0, "DiffDelete",   { bg = "#FAFAFA", fg = "#FF3333" })
hi(0, "DiffText",     { bg = "#F29718", fg = "#FAFAFA" })
hi(0, "ErrorMsg",     { fg = "#FF3333", bold = true })
hi(0, "WarningMsg",   { fg = "#F29718" })
hi(0, "ModeMsg",      { fg = "#575F66", bold = true })
hi(0, "MoreMsg",      { fg = "#86B300" })
hi(0, "SpellBad",     { undercurl = true, sp = "#FF3333" })
hi(0, "SpellCap",     { undercurl = true, sp = "#F29718" })
hi(0, "SpellLocal",   { undercurl = true, sp = "#4DBF99" })
hi(0, "SpellRare",    { undercurl = true, sp = "#A37ACC" })

-- Syntax
hi(0, "Comment",      { fg = "#5C6773", italic = true })
hi(0, "String",       { fg = "#86B300" })
hi(0, "Character",    { fg = "#86B300" })
hi(0, "Number",       { fg = "#4DBF99" })
hi(0, "Float",        { fg = "#4DBF99" })
hi(0, "Boolean",      { fg = "#FF3333" })
hi(0, "Keyword",      { fg = "#A37ACC", bold = true })
hi(0, "Statement",    { fg = "#A37ACC" })
hi(0, "Conditional",  { fg = "#A37ACC" })
hi(0, "Repeat",       { fg = "#A37ACC" })
hi(0, "Label",        { fg = "#41A6D9" })
hi(0, "Operator",     { fg = "#A37ACC" })
hi(0, "Exception",    { fg = "#FF3333" })
hi(0, "Function",     { fg = "#41A6D9" })
hi(0, "Identifier",   { fg = "#4DBF99" })
hi(0, "Type",         { fg = "#F29718" })
hi(0, "StorageClass", { fg = "#A37ACC" })
hi(0, "Structure",    { fg = "#F29718" })
hi(0, "Typedef",      { fg = "#F29718" })
hi(0, "Constant",     { fg = "#FF3333" })
hi(0, "PreProc",      { fg = "#4DBF99" })
hi(0, "Include",      { fg = "#A37ACC" })
hi(0, "Define",       { fg = "#A37ACC" })
hi(0, "Macro",        { fg = "#4DBF99" })
hi(0, "Special",      { fg = "#FF3333" })
hi(0, "SpecialChar",  { fg = "#4DBF99" })
hi(0, "Delimiter",    { fg = "#575F66" })
hi(0, "Tag",          { fg = "#FF3333" })
hi(0, "Debug",        { fg = "#FF3333" })
hi(0, "Error",        { fg = "#FF3333", bold = true })
hi(0, "Todo",         { bg = "#F29718", fg = "#FAFAFA", bold = true })
hi(0, "Underlined",   { underline = true })

-- Treesitter
hi(0, "@comment",            { link = "Comment" })
hi(0, "@comment.todo",       { bg = "#F29718", fg = "#FAFAFA", bold = true })
hi(0, "@string",             { link = "String" })
hi(0, "@string.regexp",      { fg = "#4DBF99" })
hi(0, "@string.escape",      { fg = "#4DBF99" })
hi(0, "@number",             { link = "Number" })
hi(0, "@float",              { link = "Float" })
hi(0, "@boolean",            { link = "Boolean" })
hi(0, "@keyword",            { link = "Keyword" })
hi(0, "@keyword.function",   { fg = "#A37ACC" })
hi(0, "@keyword.return",     { fg = "#A37ACC", bold = true })
hi(0, "@keyword.operator",   { fg = "#A37ACC" })
hi(0, "@function",           { link = "Function" })
hi(0, "@function.call",      { fg = "#41A6D9" })
hi(0, "@function.macro",     { fg = "#4DBF99" })
hi(0, "@function.builtin",   { fg = "#4DBF99" })
hi(0, "@method",             { fg = "#41A6D9" })
hi(0, "@method.call",        { fg = "#41A6D9" })
hi(0, "@constructor",        { fg = "#41A6D9" })
hi(0, "@type",               { link = "Type" })
hi(0, "@type.builtin",       { fg = "#F29718", italic = true })
hi(0, "@variable",           { fg = "#575F66" })
hi(0, "@variable.builtin",   { fg = "#FF3333" })
hi(0, "@variable.parameter", { fg = "#575F66", italic = true })
hi(0, "@property",           { fg = "#575F66" })
hi(0, "@field",              { fg = "#575F66" })
hi(0, "@constant",           { link = "Constant" })
hi(0, "@constant.builtin",   { fg = "#FF3333", italic = true })
hi(0, "@namespace",          { fg = "#4DBF99" })
hi(0, "@attribute",          { fg = "#41A6D9" })
hi(0, "@operator",           { fg = "#A37ACC" })
hi(0, "@punctuation",        { fg = "#575F66" })
hi(0, "@tag",                { fg = "#FF3333" })
hi(0, "@tag.attribute",      { fg = "#41A6D9" })
hi(0, "@tag.delimiter",      { fg = "#5C6773" })
hi(0, "@text.uri",           { fg = "#4DBF99", underline = true })
hi(0, "@text.reference",     { fg = "#41A6D9" })

-- LSP
hi(0, "DiagnosticError",          { fg = "#FF3333" })
hi(0, "DiagnosticWarn",           { fg = "#F29718" })
hi(0, "DiagnosticInfo",           { fg = "#41A6D9" })
hi(0, "DiagnosticHint",           { fg = "#4DBF99" })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#FF3333" })
hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#F29718" })
hi(0, "LspReferenceText",         { bg = "#D3D3D3" })
hi(0, "LspReferenceRead",         { bg = "#D3D3D3" })
hi(0, "LspReferenceWrite",        { bg = "#D3D3D3", bold = true })
