-- Theme: Catppuccin Latte
-- Source: https://catppuccin.com
-- Usage: dofile(vim.fn.stdpath("config") .. "/lua/rice/catppuccin-latte.lua")
--   or copy to ~/.config/nvim/colors/catppuccin-latte.lua

local hi = vim.api.nvim_set_hl

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "catppuccin-latte"

local is_light = true
vim.o.background = is_light and "light" or "dark"

-- Editor chrome
hi(0, "Normal",       { bg = "#eff1f5", fg = "#4c4f69" })
hi(0, "NormalFloat",  { bg = "#5c5f77", fg = "#4c4f69" })
hi(0, "NormalNC",     { bg = "#eff1f5", fg = "#6c6f85" })
hi(0, "SignColumn",   { bg = "#eff1f5" })
hi(0, "LineNr",       { fg = "#6c6f85" })
hi(0, "CursorLine",   { bg = "#acb0be" })
hi(0, "CursorLineNr", { fg = "#4c4f69", bold = true })
hi(0, "CursorColumn", { bg = "#acb0be" })
hi(0, "Visual",       { bg = "#acb0be" })
hi(0, "VisualNOS",    { bg = "#acb0be" })
hi(0, "Search",       { bg = "#df8e1d", fg = "#eff1f5" })
hi(0, "IncSearch",    { bg = "#df8e1d", fg = "#eff1f5" })
hi(0, "CurSearch",    { bg = "#df8e1d", fg = "#eff1f5" })
hi(0, "StatusLine",   { bg = "#5c5f77", fg = "#4c4f69" })
hi(0, "StatusLineNC", { bg = "#5c5f77", fg = "#6c6f85" })
hi(0, "VertSplit",    { fg = "#6c6f85" })
hi(0, "WinSeparator", { fg = "#6c6f85" })
hi(0, "Folded",       { bg = "#5c5f77", fg = "#6c6f85" })
hi(0, "FoldColumn",   { fg = "#6c6f85" })
hi(0, "Conceal",      { fg = "#6c6f85" })
hi(0, "ColorColumn",  { bg = "#5c5f77" })
hi(0, "Pmenu",        { bg = "#5c5f77", fg = "#4c4f69" })
hi(0, "PmenuSel",     { bg = "#1e66f5", fg = "#eff1f5" })
hi(0, "PmenuSbar",    { bg = "#5c5f77" })
hi(0, "PmenuThumb",   { bg = "#6c6f85" })
hi(0, "TabLine",      { bg = "#5c5f77", fg = "#6c6f85" })
hi(0, "TabLineSel",   { bg = "#eff1f5", fg = "#4c4f69", bold = true })
hi(0, "TabLineFill",  { bg = "#5c5f77" })
hi(0, "Title",        { fg = "#1e66f5", bold = true })
hi(0, "MatchParen",   { fg = "#179299", bold = true })
hi(0, "Question",     { fg = "#40a02b" })
hi(0, "Directory",    { fg = "#1e66f5" })
hi(0, "SpecialKey",   { fg = "#6c6f85" })
hi(0, "NonText",      { fg = "#6c6f85" })
hi(0, "Whitespace",   { fg = "#6c6f85" })
hi(0, "EndOfBuffer",  { fg = "#6c6f85" })
hi(0, "WildMenu",     { bg = "#1e66f5", fg = "#eff1f5" })
hi(0, "DiffAdd",      { bg = "#eff1f5", fg = "#40a02b" })
hi(0, "DiffChange",   { bg = "#eff1f5", fg = "#df8e1d" })
hi(0, "DiffDelete",   { bg = "#eff1f5", fg = "#d20f39" })
hi(0, "DiffText",     { bg = "#df8e1d", fg = "#eff1f5" })
hi(0, "ErrorMsg",     { fg = "#d20f39", bold = true })
hi(0, "WarningMsg",   { fg = "#df8e1d" })
hi(0, "ModeMsg",      { fg = "#4c4f69", bold = true })
hi(0, "MoreMsg",      { fg = "#40a02b" })
hi(0, "SpellBad",     { undercurl = true, sp = "#d20f39" })
hi(0, "SpellCap",     { undercurl = true, sp = "#df8e1d" })
hi(0, "SpellLocal",   { undercurl = true, sp = "#179299" })
hi(0, "SpellRare",    { undercurl = true, sp = "#ea76cb" })

-- Syntax
hi(0, "Comment",      { fg = "#6c6f85", italic = true })
hi(0, "String",       { fg = "#40a02b" })
hi(0, "Character",    { fg = "#40a02b" })
hi(0, "Number",       { fg = "#179299" })
hi(0, "Float",        { fg = "#179299" })
hi(0, "Boolean",      { fg = "#d20f39" })
hi(0, "Keyword",      { fg = "#ea76cb", bold = true })
hi(0, "Statement",    { fg = "#ea76cb" })
hi(0, "Conditional",  { fg = "#ea76cb" })
hi(0, "Repeat",       { fg = "#ea76cb" })
hi(0, "Label",        { fg = "#1e66f5" })
hi(0, "Operator",     { fg = "#ea76cb" })
hi(0, "Exception",    { fg = "#d20f39" })
hi(0, "Function",     { fg = "#1e66f5" })
hi(0, "Identifier",   { fg = "#179299" })
hi(0, "Type",         { fg = "#df8e1d" })
hi(0, "StorageClass", { fg = "#ea76cb" })
hi(0, "Structure",    { fg = "#df8e1d" })
hi(0, "Typedef",      { fg = "#df8e1d" })
hi(0, "Constant",     { fg = "#d20f39" })
hi(0, "PreProc",      { fg = "#179299" })
hi(0, "Include",      { fg = "#ea76cb" })
hi(0, "Define",       { fg = "#ea76cb" })
hi(0, "Macro",        { fg = "#179299" })
hi(0, "Special",      { fg = "#d20f39" })
hi(0, "SpecialChar",  { fg = "#179299" })
hi(0, "Delimiter",    { fg = "#4c4f69" })
hi(0, "Tag",          { fg = "#d20f39" })
hi(0, "Debug",        { fg = "#d20f39" })
hi(0, "Error",        { fg = "#d20f39", bold = true })
hi(0, "Todo",         { bg = "#df8e1d", fg = "#eff1f5", bold = true })
hi(0, "Underlined",   { underline = true })

-- Treesitter
hi(0, "@comment",            { link = "Comment" })
hi(0, "@comment.todo",       { bg = "#df8e1d", fg = "#eff1f5", bold = true })
hi(0, "@string",             { link = "String" })
hi(0, "@string.regexp",      { fg = "#179299" })
hi(0, "@string.escape",      { fg = "#179299" })
hi(0, "@number",             { link = "Number" })
hi(0, "@float",              { link = "Float" })
hi(0, "@boolean",            { link = "Boolean" })
hi(0, "@keyword",            { link = "Keyword" })
hi(0, "@keyword.function",   { fg = "#ea76cb" })
hi(0, "@keyword.return",     { fg = "#ea76cb", bold = true })
hi(0, "@keyword.operator",   { fg = "#ea76cb" })
hi(0, "@function",           { link = "Function" })
hi(0, "@function.call",      { fg = "#1e66f5" })
hi(0, "@function.macro",     { fg = "#179299" })
hi(0, "@function.builtin",   { fg = "#179299" })
hi(0, "@method",             { fg = "#1e66f5" })
hi(0, "@method.call",        { fg = "#1e66f5" })
hi(0, "@constructor",        { fg = "#1e66f5" })
hi(0, "@type",               { link = "Type" })
hi(0, "@type.builtin",       { fg = "#df8e1d", italic = true })
hi(0, "@variable",           { fg = "#4c4f69" })
hi(0, "@variable.builtin",   { fg = "#d20f39" })
hi(0, "@variable.parameter", { fg = "#4c4f69", italic = true })
hi(0, "@property",           { fg = "#4c4f69" })
hi(0, "@field",              { fg = "#4c4f69" })
hi(0, "@constant",           { link = "Constant" })
hi(0, "@constant.builtin",   { fg = "#d20f39", italic = true })
hi(0, "@namespace",          { fg = "#179299" })
hi(0, "@attribute",          { fg = "#1e66f5" })
hi(0, "@operator",           { fg = "#ea76cb" })
hi(0, "@punctuation",        { fg = "#4c4f69" })
hi(0, "@tag",                { fg = "#d20f39" })
hi(0, "@tag.attribute",      { fg = "#1e66f5" })
hi(0, "@tag.delimiter",      { fg = "#6c6f85" })
hi(0, "@text.uri",           { fg = "#179299", underline = true })
hi(0, "@text.reference",     { fg = "#1e66f5" })

-- LSP
hi(0, "DiagnosticError",          { fg = "#d20f39" })
hi(0, "DiagnosticWarn",           { fg = "#df8e1d" })
hi(0, "DiagnosticInfo",           { fg = "#1e66f5" })
hi(0, "DiagnosticHint",           { fg = "#179299" })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#d20f39" })
hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#df8e1d" })
hi(0, "LspReferenceText",         { bg = "#acb0be" })
hi(0, "LspReferenceRead",         { bg = "#acb0be" })
hi(0, "LspReferenceWrite",        { bg = "#acb0be", bold = true })
