-- Theme: Material Dark
-- Source: https://material-theme.com
-- Usage: dofile(vim.fn.stdpath("config") .. "/lua/rice/material-dark.lua")
--   or copy to ~/.config/nvim/colors/material-dark.lua

local hi = vim.api.nvim_set_hl

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "material-dark"

local is_light = false
vim.o.background = is_light and "light" or "dark"

-- Editor chrome
hi(0, "Normal",       { bg = "#212121", fg = "#EEFFFF" })
hi(0, "NormalFloat",  { bg = "#546E7A", fg = "#EEFFFF" })
hi(0, "NormalNC",     { bg = "#212121", fg = "#B0BEC5" })
hi(0, "SignColumn",   { bg = "#212121" })
hi(0, "LineNr",       { fg = "#B0BEC5" })
hi(0, "CursorLine",   { bg = "#546E7A" })
hi(0, "CursorLineNr", { fg = "#EEFFFF", bold = true })
hi(0, "CursorColumn", { bg = "#546E7A" })
hi(0, "Visual",       { bg = "#546E7A" })
hi(0, "VisualNOS",    { bg = "#546E7A" })
hi(0, "Search",       { bg = "#FFCB6B", fg = "#212121" })
hi(0, "IncSearch",    { bg = "#FFCB6B", fg = "#212121" })
hi(0, "CurSearch",    { bg = "#FFCB6B", fg = "#212121" })
hi(0, "StatusLine",   { bg = "#546E7A", fg = "#EEFFFF" })
hi(0, "StatusLineNC", { bg = "#546E7A", fg = "#B0BEC5" })
hi(0, "VertSplit",    { fg = "#B0BEC5" })
hi(0, "WinSeparator", { fg = "#B0BEC5" })
hi(0, "Folded",       { bg = "#546E7A", fg = "#B0BEC5" })
hi(0, "FoldColumn",   { fg = "#B0BEC5" })
hi(0, "Conceal",      { fg = "#B0BEC5" })
hi(0, "ColorColumn",  { bg = "#546E7A" })
hi(0, "Pmenu",        { bg = "#546E7A", fg = "#EEFFFF" })
hi(0, "PmenuSel",     { bg = "#82AAFF", fg = "#212121" })
hi(0, "PmenuSbar",    { bg = "#546E7A" })
hi(0, "PmenuThumb",   { bg = "#B0BEC5" })
hi(0, "TabLine",      { bg = "#546E7A", fg = "#B0BEC5" })
hi(0, "TabLineSel",   { bg = "#212121", fg = "#EEFFFF", bold = true })
hi(0, "TabLineFill",  { bg = "#546E7A" })
hi(0, "Title",        { fg = "#82AAFF", bold = true })
hi(0, "MatchParen",   { fg = "#89DDFF", bold = true })
hi(0, "Question",     { fg = "#C3E88D" })
hi(0, "Directory",    { fg = "#82AAFF" })
hi(0, "SpecialKey",   { fg = "#B0BEC5" })
hi(0, "NonText",      { fg = "#B0BEC5" })
hi(0, "Whitespace",   { fg = "#B0BEC5" })
hi(0, "EndOfBuffer",  { fg = "#B0BEC5" })
hi(0, "WildMenu",     { bg = "#82AAFF", fg = "#212121" })
hi(0, "DiffAdd",      { bg = "#212121", fg = "#C3E88D" })
hi(0, "DiffChange",   { bg = "#212121", fg = "#FFCB6B" })
hi(0, "DiffDelete",   { bg = "#212121", fg = "#FF5370" })
hi(0, "DiffText",     { bg = "#FFCB6B", fg = "#212121" })
hi(0, "ErrorMsg",     { fg = "#FF5370", bold = true })
hi(0, "WarningMsg",   { fg = "#FFCB6B" })
hi(0, "ModeMsg",      { fg = "#EEFFFF", bold = true })
hi(0, "MoreMsg",      { fg = "#C3E88D" })
hi(0, "SpellBad",     { undercurl = true, sp = "#FF5370" })
hi(0, "SpellCap",     { undercurl = true, sp = "#FFCB6B" })
hi(0, "SpellLocal",   { undercurl = true, sp = "#89DDFF" })
hi(0, "SpellRare",    { undercurl = true, sp = "#C792EA" })

-- Syntax
hi(0, "Comment",      { fg = "#B0BEC5", italic = true })
hi(0, "String",       { fg = "#C3E88D" })
hi(0, "Character",    { fg = "#C3E88D" })
hi(0, "Number",       { fg = "#89DDFF" })
hi(0, "Float",        { fg = "#89DDFF" })
hi(0, "Boolean",      { fg = "#FF5370" })
hi(0, "Keyword",      { fg = "#C792EA", bold = true })
hi(0, "Statement",    { fg = "#C792EA" })
hi(0, "Conditional",  { fg = "#C792EA" })
hi(0, "Repeat",       { fg = "#C792EA" })
hi(0, "Label",        { fg = "#82AAFF" })
hi(0, "Operator",     { fg = "#C792EA" })
hi(0, "Exception",    { fg = "#FF5370" })
hi(0, "Function",     { fg = "#82AAFF" })
hi(0, "Identifier",   { fg = "#89DDFF" })
hi(0, "Type",         { fg = "#FFCB6B" })
hi(0, "StorageClass", { fg = "#C792EA" })
hi(0, "Structure",    { fg = "#FFCB6B" })
hi(0, "Typedef",      { fg = "#FFCB6B" })
hi(0, "Constant",     { fg = "#FF5370" })
hi(0, "PreProc",      { fg = "#89DDFF" })
hi(0, "Include",      { fg = "#C792EA" })
hi(0, "Define",       { fg = "#C792EA" })
hi(0, "Macro",        { fg = "#89DDFF" })
hi(0, "Special",      { fg = "#FF5370" })
hi(0, "SpecialChar",  { fg = "#89DDFF" })
hi(0, "Delimiter",    { fg = "#EEFFFF" })
hi(0, "Tag",          { fg = "#FF5370" })
hi(0, "Debug",        { fg = "#FF5370" })
hi(0, "Error",        { fg = "#FF5370", bold = true })
hi(0, "Todo",         { bg = "#FFCB6B", fg = "#212121", bold = true })
hi(0, "Underlined",   { underline = true })

-- Treesitter
hi(0, "@comment",            { link = "Comment" })
hi(0, "@comment.todo",       { bg = "#FFCB6B", fg = "#212121", bold = true })
hi(0, "@string",             { link = "String" })
hi(0, "@string.regexp",      { fg = "#89DDFF" })
hi(0, "@string.escape",      { fg = "#89DDFF" })
hi(0, "@number",             { link = "Number" })
hi(0, "@float",              { link = "Float" })
hi(0, "@boolean",            { link = "Boolean" })
hi(0, "@keyword",            { link = "Keyword" })
hi(0, "@keyword.function",   { fg = "#C792EA" })
hi(0, "@keyword.return",     { fg = "#C792EA", bold = true })
hi(0, "@keyword.operator",   { fg = "#C792EA" })
hi(0, "@function",           { link = "Function" })
hi(0, "@function.call",      { fg = "#82AAFF" })
hi(0, "@function.macro",     { fg = "#89DDFF" })
hi(0, "@function.builtin",   { fg = "#89DDFF" })
hi(0, "@method",             { fg = "#82AAFF" })
hi(0, "@method.call",        { fg = "#82AAFF" })
hi(0, "@constructor",        { fg = "#82AAFF" })
hi(0, "@type",               { link = "Type" })
hi(0, "@type.builtin",       { fg = "#FFCB6B", italic = true })
hi(0, "@variable",           { fg = "#EEFFFF" })
hi(0, "@variable.builtin",   { fg = "#FF5370" })
hi(0, "@variable.parameter", { fg = "#EEFFFF", italic = true })
hi(0, "@property",           { fg = "#EEFFFF" })
hi(0, "@field",              { fg = "#EEFFFF" })
hi(0, "@constant",           { link = "Constant" })
hi(0, "@constant.builtin",   { fg = "#FF5370", italic = true })
hi(0, "@namespace",          { fg = "#89DDFF" })
hi(0, "@attribute",          { fg = "#82AAFF" })
hi(0, "@operator",           { fg = "#C792EA" })
hi(0, "@punctuation",        { fg = "#EEFFFF" })
hi(0, "@tag",                { fg = "#FF5370" })
hi(0, "@tag.attribute",      { fg = "#82AAFF" })
hi(0, "@tag.delimiter",      { fg = "#B0BEC5" })
hi(0, "@text.uri",           { fg = "#89DDFF", underline = true })
hi(0, "@text.reference",     { fg = "#82AAFF" })

-- LSP
hi(0, "DiagnosticError",          { fg = "#FF5370" })
hi(0, "DiagnosticWarn",           { fg = "#FFCB6B" })
hi(0, "DiagnosticInfo",           { fg = "#82AAFF" })
hi(0, "DiagnosticHint",           { fg = "#89DDFF" })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#FF5370" })
hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#FFCB6B" })
hi(0, "LspReferenceText",         { bg = "#546E7A" })
hi(0, "LspReferenceRead",         { bg = "#546E7A" })
hi(0, "LspReferenceWrite",        { bg = "#546E7A", bold = true })
