-- Theme: Nightfox
-- Source: https://github.com/EdenEast/nightfox.nvim
-- Usage: dofile(vim.fn.stdpath("config") .. "/lua/rice/nightfox.lua")
--   or copy to ~/.config/nvim/colors/nightfox.lua

local hi = vim.api.nvim_set_hl

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "nightfox"

local is_light = false
vim.o.background = is_light and "light" or "dark"

-- Editor chrome
hi(0, "Normal",       { bg = "#192330", fg = "#CDCECF" })
hi(0, "NormalFloat",  { bg = "#393B44", fg = "#CDCECF" })
hi(0, "NormalNC",     { bg = "#192330", fg = "#575860" })
hi(0, "SignColumn",   { bg = "#192330" })
hi(0, "LineNr",       { fg = "#575860" })
hi(0, "CursorLine",   { bg = "#2B3B51" })
hi(0, "CursorLineNr", { fg = "#CDCECF", bold = true })
hi(0, "CursorColumn", { bg = "#2B3B51" })
hi(0, "Visual",       { bg = "#2B3B51" })
hi(0, "VisualNOS",    { bg = "#2B3B51" })
hi(0, "Search",       { bg = "#DBC074", fg = "#192330" })
hi(0, "IncSearch",    { bg = "#E0C989", fg = "#192330" })
hi(0, "CurSearch",    { bg = "#E0C989", fg = "#192330" })
hi(0, "StatusLine",   { bg = "#393B44", fg = "#CDCECF" })
hi(0, "StatusLineNC", { bg = "#393B44", fg = "#575860" })
hi(0, "VertSplit",    { fg = "#575860" })
hi(0, "WinSeparator", { fg = "#575860" })
hi(0, "Folded",       { bg = "#393B44", fg = "#575860" })
hi(0, "FoldColumn",   { fg = "#575860" })
hi(0, "Conceal",      { fg = "#575860" })
hi(0, "ColorColumn",  { bg = "#393B44" })
hi(0, "Pmenu",        { bg = "#393B44", fg = "#CDCECF" })
hi(0, "PmenuSel",     { bg = "#719CD6", fg = "#192330" })
hi(0, "PmenuSbar",    { bg = "#393B44" })
hi(0, "PmenuThumb",   { bg = "#575860" })
hi(0, "TabLine",      { bg = "#393B44", fg = "#575860" })
hi(0, "TabLineSel",   { bg = "#192330", fg = "#CDCECF", bold = true })
hi(0, "TabLineFill",  { bg = "#393B44" })
hi(0, "Title",        { fg = "#719CD6", bold = true })
hi(0, "MatchParen",   { fg = "#63CDCF", bold = true })
hi(0, "Question",     { fg = "#81B29A" })
hi(0, "Directory",    { fg = "#719CD6" })
hi(0, "SpecialKey",   { fg = "#575860" })
hi(0, "NonText",      { fg = "#575860" })
hi(0, "Whitespace",   { fg = "#575860" })
hi(0, "EndOfBuffer",  { fg = "#575860" })
hi(0, "WildMenu",     { bg = "#719CD6", fg = "#192330" })
hi(0, "DiffAdd",      { bg = "#192330", fg = "#81B29A" })
hi(0, "DiffChange",   { bg = "#192330", fg = "#DBC074" })
hi(0, "DiffDelete",   { bg = "#192330", fg = "#C94F6D" })
hi(0, "DiffText",     { bg = "#DBC074", fg = "#192330" })
hi(0, "ErrorMsg",     { fg = "#C94F6D", bold = true })
hi(0, "WarningMsg",   { fg = "#DBC074" })
hi(0, "ModeMsg",      { fg = "#CDCECF", bold = true })
hi(0, "MoreMsg",      { fg = "#81B29A" })
hi(0, "SpellBad",     { undercurl = true, sp = "#C94F6D" })
hi(0, "SpellCap",     { undercurl = true, sp = "#DBC074" })
hi(0, "SpellLocal",   { undercurl = true, sp = "#63CDCF" })
hi(0, "SpellRare",    { undercurl = true, sp = "#9D79D6" })

-- Syntax
hi(0, "Comment",      { fg = "#575860", italic = true })
hi(0, "String",       { fg = "#81B29A" })
hi(0, "Character",    { fg = "#81B29A" })
hi(0, "Number",       { fg = "#63CDCF" })
hi(0, "Float",        { fg = "#63CDCF" })
hi(0, "Boolean",      { fg = "#C94F6D" })
hi(0, "Keyword",      { fg = "#9D79D6", bold = true })
hi(0, "Statement",    { fg = "#9D79D6" })
hi(0, "Conditional",  { fg = "#9D79D6" })
hi(0, "Repeat",       { fg = "#9D79D6" })
hi(0, "Label",        { fg = "#719CD6" })
hi(0, "Operator",     { fg = "#9D79D6" })
hi(0, "Exception",    { fg = "#C94F6D" })
hi(0, "Function",     { fg = "#719CD6" })
hi(0, "Identifier",   { fg = "#63CDCF" })
hi(0, "Type",         { fg = "#DBC074" })
hi(0, "StorageClass", { fg = "#9D79D6" })
hi(0, "Structure",    { fg = "#DBC074" })
hi(0, "Typedef",      { fg = "#DBC074" })
hi(0, "Constant",     { fg = "#C94F6D" })
hi(0, "PreProc",      { fg = "#63CDCF" })
hi(0, "Include",      { fg = "#9D79D6" })
hi(0, "Define",       { fg = "#9D79D6" })
hi(0, "Macro",        { fg = "#63CDCF" })
hi(0, "Special",      { fg = "#C94F6D" })
hi(0, "SpecialChar",  { fg = "#63CDCF" })
hi(0, "Delimiter",    { fg = "#CDCECF" })
hi(0, "Tag",          { fg = "#C94F6D" })
hi(0, "Debug",        { fg = "#C94F6D" })
hi(0, "Error",        { fg = "#C94F6D", bold = true })
hi(0, "Todo",         { bg = "#DBC074", fg = "#192330", bold = true })
hi(0, "Underlined",   { underline = true })

-- Treesitter
hi(0, "@comment",            { link = "Comment" })
hi(0, "@comment.todo",       { bg = "#DBC074", fg = "#192330", bold = true })
hi(0, "@string",             { link = "String" })
hi(0, "@string.regexp",      { fg = "#63CDCF" })
hi(0, "@string.escape",      { fg = "#63CDCF" })
hi(0, "@number",             { link = "Number" })
hi(0, "@float",              { link = "Float" })
hi(0, "@boolean",            { link = "Boolean" })
hi(0, "@keyword",            { link = "Keyword" })
hi(0, "@keyword.function",   { fg = "#9D79D6" })
hi(0, "@keyword.return",     { fg = "#9D79D6", bold = true })
hi(0, "@keyword.operator",   { fg = "#9D79D6" })
hi(0, "@function",           { link = "Function" })
hi(0, "@function.call",      { fg = "#719CD6" })
hi(0, "@function.macro",     { fg = "#63CDCF" })
hi(0, "@function.builtin",   { fg = "#63CDCF" })
hi(0, "@method",             { fg = "#719CD6" })
hi(0, "@method.call",        { fg = "#719CD6" })
hi(0, "@constructor",        { fg = "#719CD6" })
hi(0, "@type",               { link = "Type" })
hi(0, "@type.builtin",       { fg = "#DBC074", italic = true })
hi(0, "@variable",           { fg = "#CDCECF" })
hi(0, "@variable.builtin",   { fg = "#C94F6D" })
hi(0, "@variable.parameter", { fg = "#CDCECF", italic = true })
hi(0, "@property",           { fg = "#CDCECF" })
hi(0, "@field",              { fg = "#CDCECF" })
hi(0, "@constant",           { link = "Constant" })
hi(0, "@constant.builtin",   { fg = "#C94F6D", italic = true })
hi(0, "@namespace",          { fg = "#63CDCF" })
hi(0, "@attribute",          { fg = "#719CD6" })
hi(0, "@operator",           { fg = "#9D79D6" })
hi(0, "@punctuation",        { fg = "#CDCECF" })
hi(0, "@tag",                { fg = "#C94F6D" })
hi(0, "@tag.attribute",      { fg = "#719CD6" })
hi(0, "@tag.delimiter",      { fg = "#575860" })
hi(0, "@text.uri",           { fg = "#63CDCF", underline = true })
hi(0, "@text.reference",     { fg = "#719CD6" })

-- LSP
hi(0, "DiagnosticError",          { fg = "#C94F6D" })
hi(0, "DiagnosticWarn",           { fg = "#DBC074" })
hi(0, "DiagnosticInfo",           { fg = "#719CD6" })
hi(0, "DiagnosticHint",           { fg = "#63CDCF" })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#C94F6D" })
hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#DBC074" })
hi(0, "LspReferenceText",         { bg = "#2B3B51" })
hi(0, "LspReferenceRead",         { bg = "#2B3B51" })
hi(0, "LspReferenceWrite",        { bg = "#2B3B51", bold = true })
